"""Ingredient table updated

Revision ID: f35bf66d6d65
Revises: 5088979dc35a
Create Date: 2018-12-07 10:29:28.704630

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f35bf66d6d65'
down_revision = '5088979dc35a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'ingredient', ['name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'ingredient', type_='unique')
    # ### end Alembic commands ###
